FROM nginx
RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/* \
HEALTHCHECK --interval=5s --timeout=3s --retries=5 \
            CMD curl -f http://localhost||exit 1