FROM ubuntu
#RUN sed -i s@http://ports.ubuntu.com@http://mirrors.tuna.tsinghua.edu.cn@g /etc/apt/sources.list && apt-get update
#RUN apt-get -y install aufs-tools&& apt-get clean
#CMD echo $HOME
CMD ["sh","-c","echo $HOME"]